import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { BiChevronRight } from "react-icons/bi";
import { BsCart4 } from "react-icons/bs";
import Link from "next/link";
import Product_Card from "../components/home/Product_Card";

export default function Home({ products_tc, products, products_f }) {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch({
      type: "addToState",
      payload: products,
    });
  });

  // const productList = products.map((product) => {
  //   <Product_Card key={product._id} product={product} />;
  // });

  return (
    <div className="home">
      <Head>
        <title>Bizmerce</title>
        <meta name="description" content="Generated by create next home" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="home_main">
        <div className="home__first_page">
          <div className="home__first_page__left">
            <h1>Every Purchase Will Be Made With Pleasure</h1>
            <h2 className="home__first_page__left_h2">
              Buying and selling of goods or services using internet.
            </h2>
            <Link href="/store">
              <a>
                <div className="home__button__shop">
                  <h2>Start Shopping</h2>
                  <div className="home__button__shop__icon">
                    <BiChevronRight className="icon n" />
                  </div>
                </div>
              </a>
            </Link>
          </div>
          <div className="home__first_page__right">
            <div className="home__first_page__right__img">
              <img
                className="home__first_page__right__img_"
                src="/home_img.png"
                alt="vector"
              />
              <div className="home__first_page__right__offer">
                <h4>Offer</h4>
                <h2>20% Off</h2>
                <h3>10 Amazing Products</h3>
              </div>
              <div className="home__first_page__right__offer_">
                <BsCart4 className="icon v" />
              </div>
            </div>
          </div>
        </div>
        <div className="home__banners">
          <div className="home__banners__">
            <h1>Featured</h1>
            <div className="home__line" />
          </div>
          <div className="home__banners_">
            <div className="home__banner">
              <img className="banner_img" src="/banner_1.jpg" alt="banner" />
              <div className="home__banner_">
                <h3>Save 30%</h3>
                <h2>Men</h2>
              </div>
            </div>
            <div className="home__banner">
              <img className="banner_img" src="/banner_2.jpg" alt="banner" />
              <div className="home__banner_">
                <h3>Save 60%</h3>
                <h2>Headset</h2>
              </div>
            </div>
            <div className="home__banner">
              <img className="banner_img" src="/banner_3.jpg" alt="banner" />
              <div className="home__banner_">
                <h3>Save 60%</h3>
                <h2>Footware</h2>
              </div>
            </div>
            <div className="home__banner">
              <img className="banner_img" src="/banner_4.jpg" alt="banner" />
              <div className="_1">
                <h3>Save 10%</h3>
                <h2>Gifts</h2>
              </div>
            </div>
          </div>
        </div>
        <div className="home__top_collection">
          <div className="home__top_collection__head">
            <h4>Special Offer</h4>
            <h2>Top Collection</h2>
            <div className="home__line" />
          </div>
          <div className="home__top_collection_">
            {products_tc &&
              products_tc.products.map((product) => (
                <Product_Card key={product._id} product={product} />
              ))}
          </div>
        </div>
        <div className="home__top_collection">
          <div className="home__top_collection__head">
            <h4>Recommended For You</h4>
            <h2>Featured</h2>
            <div className="home__line" />
          </div>
          <div className="home__top_collection_">
            {products_f &&
              products_f.products.map((product) => (
                <Product_Card key={product._id} product={product} />
              ))}
          </div>
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res_tc = await fetch(
    `https://bizmerce-server.cwd-harshit.repl.co/api/v1/products?special=Top_Collections`
  );
  const data_tc = await res_tc.json();
  const res_f = await fetch(
    `https://bizmerce-server.cwd-harshit.repl.co/api/v1/products?special=Featured`
  );
  const data_f = await res_f.json();
  // const res = await fetch(`https://bizmerce-server.cwd-harshit.repl.co/api/v1/products`);
  // const data = await res.json();
  return {
    props: {
      products_tc: data_tc,
      // products: data,
      products_f: data_f,
    },
  };
}
